### ISSUE TITLE
Thanks for copying the repo without mention/forking it! Great work ;)

### ISSUE THREAD

**Issue by ptr1337** [Gontier-Julien/Linux-YAOK#1]
https://wiki.archlinux.org/title/AUR_submission_guidelines

https://github.com/cachyos/linux-cachyos

Watching your commit history, seems like its mostly a complete copy of mine work. 
Good luck with your project!

**Comment by Gontier-Julien** [comment]
Forgot to add some mentions, thank for reminding me, i'll do it now, sorry about that.
Are you still okay with this repo being present?
Again i'm sorry

**Comment by ptr1337** [comment]
Yeah, what should i do. A fork is in general the best idea. You can do it, and push your stuff in. How you wish to. 
Regards.

**Comment by Gontier-Julien** [comment]
Thank you for your understanding and being kind about it
